# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Memex (beta)
email: martinek@kisk.cz
description: > # this means to ignore newlines until "baseurl:"
  Karty s vědomostmi z informační vědy
baseurl: "/memex" # the subpath of your site, e.g. /blog
twitter_username: kiskffmu
github_username:  kisk-ff-mu

collections:
  categories:
    output: true


# Build settings
markdown: kramdown
